config/routes.rb
Ibc::Application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'reports/:type/new' => 'reports#new', :as => 'new_reports'
  
  resources :user_sessions
  resources :users
  resources :reports, :except => [:new]
  resources :users
  
  root :to => 'reports#index'
  

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]
  
  def new
    @user = User.new
  end
  
  def create
    respond_to do |format|
      if @user = login(params[:email],params[:password],params[:remember])
        format.html { redirect_back_or_to(reports_path, :notice => 'Login successfull.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    logout
    redirect_to(login_path, :notice => 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <fieldset>
    <div class="clearfix">
      <%= label_tag :email %>
      <div class="input">
        <%= text_field_tag :email,nil, :class => 'span5' %>
        <span class="help-block"> email </span>
      </div>
    </div>
    <div class="clearfix">
      <%= label_tag :password %>
      <div class="input">
        <%= password_field_tag :password,nil, :class => 'span5' %>
        <span class="help-block"> email </span>
      </div>
    </div>
  	<div class="input input-prepend clearfix">  
      <div class="add-on"><%= check_box_tag :remember %></div>
      <label class="prependedLabel" style="font-size: 12px"> keep me logged in </label>
    </div>
    <div class="actions">
      <%= submit_tag "Login", :class => 'btn' %>
    </div>
  </fieldset>  
<% end %>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="header indent1"><h1>Welcome to IBC application</h1></div>

<%= render 'form' %>