config/routes.rb
Ibc::Application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'reports/:type/new' => 'reports#new', :as => 'new_reports'
  
  resources :user_sessions
  resources :users
  resources :reports, :except => [:new]
  resources :users
  
  root :to => 'reports#index'
  

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :report_type
  belongs_to :user
  belongs_to :updated_by, :class_name => 'User', :foreign_key => 'updated_user_id'
  belongs_to :created_by, :class_name => 'User', :foreign_key => 'created_user_id'
  
  has_one :general_report
  has_one :owner_report
  has_one :historical_report
  has_one :status_report
  has_one :supplementary_data_report
  has_one :technical_card_report
  has_one :location_report
  
  accepts_nested_attributes_for :general_report
  accepts_nested_attributes_for :owner_report  
  accepts_nested_attributes_for :historical_report
  accepts_nested_attributes_for :status_report
  accepts_nested_attributes_for :supplementary_data_report
  accepts_nested_attributes_for :technical_card_report
  accepts_nested_attributes_for :location_report
  
  validates :report_type_id, :presence => true
  
  def self.search(q)
    GeneralReport.where('name LIKE ?', "%#{q}%").map{|gr| gr.report}
  end
  
  def build_dependencies
    build_general_report
    build_owner_report
    build_historical_report
    build_status_report
    build_supplementary_data_report
    build_technical_card_report
    build_location_report
  end
    
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
  ARCHIVES= "Archives"
  ARCHITECTURE = "Architecture"
  MOBILES = "Moviles"
  INMATERIAL = "Inmaterial"
  CELEBRATIONS = "Celebrations"
  EXPRESSIONS = "Expressions"
  
  ARCHIVES_ID = 1
  ARCHITECTURE_ID = 2
  MOBILES_ID = 3
  INMATERIAL_ID = 4
  CELEBRATIONS_ID = 5
  EXPRESSIONS_ID = 6
  
  INMATERIALS = [ CELEBRATIONS_ID, EXPRESSIONS_ID]
  
  has_many :reports
  
  def build_information_for(report)
    report.build_dependencies
    case self.name
    when ReportType::ARCHIVES
      #report.build_archive_report
    when ReportType::MOBILES
      #report.build_mobile_report
    when ReportType::INMATERIAL
      #report.build_inmaterial_report
    when ReportType::ARCHITECTURE
      #report.build_architecture_report
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    if params[:q].nil? || params[:q].blank?
      @reports = Report.all
    else
      @reports = Report.search(params[:q])
    end    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  
  def new
    if params[:type].nil? || params[:type].blank?
      redirect_to reports_path, :alert => "You must select a report type to create a new report"
    else
      @report_type = ReportType.find_by_name(params[:type].titleize)
      @report = @report_type.reports.new
      @report_type.build_information_for(@report)
      
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @report }
      end
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])
    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'jwysiwyg/jquery.wysiwyg.css', :media => "all" %>
  <%= javascript_include_tag 'jwysiwyg/jquery.wysiwyg.js' %>
  <%= javascript_include_tag 'jwysiwyg/jquery.autoload.js' %>
  <%= javascript_include_tag 'jwysiwyg/plugins/wysiwyg.autoload.js' %>
  <%= javascript_include_tag 'jwysiwyg/plugins/wysiwyg.rmFormat.js' %>
  <%= javascript_include_tag 'jwysiwyg/plugins/wysiwyg.i18n.js' %>
  <%= javascript_include_tag 'jwysiwyg/i18n/lang.en.js' %>
  <%= javascript_include_tag 'jwysiwyg/i18n/lang.es.js' %>
  <%= javascript_include_tag 'jwysiwyg/i18n/lang.pt_br.js' %>
<% end %>
<script>
  $(document).ready(function() {
    //FIXME: Maybe fork scrollSpy to work better with multiple visible anchors
    $('#sideBarNavigationList').scrollSpy();    
    $(window).bind('scroll', relocateSideBar);
    
    
  });
    
  //FIXME: Proper namespace?
  function relocateSideBar() {
    var topScroll = $(window).scrollTop();
    var upperAnchor = 30;
    if (topScroll < upperAnchor) {
      $('.sidebar-right').css('top', (upperAnchor - topScroll) + 'px');
    } else {
      $('.sidebar-right').css('top', '0px');
    }
  }
  relocateSideBar();
</script>
<div class="sidebar-right fixed">
  <div id="sideBarNavigation">
    <h5>Report</h5>
    <ul id="sideBarNavigationList" data-scrollspy="scrollspy">
      <li><%= link_to 'General', '#general'  %></li>
      <li><%= link_to 'Owner', '#owner'  %></li>
      <li><%= link_to 'Historical', '#historical'  %></li>
      <li><%= link_to 'Location', '#location'  %></li>
      <li><%= link_to 'Status', '#status'  %></li>
      <li><%= link_to 'Sup. Data', '#supplementary_data'  %></li>
      <li><%= link_to 'Technical Card', '#technical_card' %></li>
      <li>
        <div class="actions">
          <%= link_to 'Go top', '#form-header'%>
          <%= link_to 'Finish', '#technical_card' %>
        </div>
      </li>  
    </ul> 
  </div>   
</div>
<div class="content-left">
  <div class="header" id="form-header">
    <h1> 
      <%=  action_name.titleize %> <%= controller_name.singularize.titleize %> : <%= @report.report_type.name %> 
    </h1>
  </div>
  <%= render :partial => '/layouts/errors', :locals => {:parent => @report } %>
  <%= form_for @report, :html => { :class => '' } do |f| %>
    <fieldset>
      <div class="field">
        <%= f.hidden_field :user_id, :value => 1 %>
        <%= f.hidden_field :report_type_id, :value => @report.report_type.id %>
      </div>
      <section id="general">
        <%= render :partial => 'reports/sections/general_report', :locals => { :f => f } %>
      </section>
      <section id="owner">
        <%= render :partial => 'reports/sections/owner_report', :locals => { :f => f } %>
      </section>
      <section id="historical">
        <%= render :partial => 'reports/sections/historical_report', :locals => { :f => f } %>
      </section>
      <section id="location">
        <%= render :partial => 'reports/sections/location_report', :locals => { :f => f } %>
      </section>
      <section id="status">
        <%= render :partial => 'reports/sections/status_report', :locals => { :f => f } %>
      </section>
      <section id="supplementary_data">
        <%= render :partial => 'reports/sections/supplementary_data_report', :locals => { :f => f } %>
      </section>
      <section id="technical_card">
        <%= render :partial => 'reports/sections/technical_card_report', :locals => { :f => f } %>
      </section>
      <div class="actions">
        <%= f.submit :class => 'btn primary' %>
        <%= link_to 'Cancel', @report.new_record? ? reports_path : @report, :class => 'btn' %>
      </div>
      <%= render :partial => 'user_information', :locals => { :uf => f } %>
    </fieldset>  
  <% end %>
</div>  

app/views/reports/_user_information.html.erb
<% if uf.object.new_record? %>
  <%= uf.hidden_field :created_user_id, :value => current_user.id %>
<% else %>  
  <%= uf.hidden_field :updated_user_id, :value => current_user.id %>
<% end %>  

app/views/reports/edit.html.erb
<%= render 'form' %>

app/views/reports/index.html.erb
<div class="container-fluid">
  <div class="sidebar">
    <h2> Search </h2>
    <%= form_tag reports_path, :method => :get do %>
      <%= search_field_tag 'q',nil, :placeholder => 'search', :class => 'span3'%>
      <%= submit_tag "Ok", :class => 'btn info' %>
    <% end %>  
  </div>
  <div class="content">
    <h2> Reports </h2>
    <div class="clearfix">
      <%= link_to 'New Report', "#", 'data-controls-modal' => "report-selection", :class => 'btn success', :id => 'select-report' %>
    </div>  
    <div id="report-selection" class="modal hide fade" style="display:none">
      <div class="modal-header">
        <a href="#" class="close">×</a>
        <h3>Report Selection</h3>
      </div>
      <div class="modal-body"> 
        <p>
          Seleccione un tipo de reporte que desea crear:
        </p>  
        <ul class="form">
          <% ReportType.all.each do |rp| %>
            <li>
              <div class="clearfix card">  
                <div class="icon">
                  <%= image_tag('layers_16x14.png') %> 
                </div>
                <div class="span2 text" > <%= link_to rp.name, url_for(:controller => 'reports', :action => 'new', :type => rp.name.downcase)%> 
                </div>
              </div>
              <div class="help-block"> Ficha para inventariar archivos, cartas, documentos, etc</div>
            </li>  
          <% end %> 
        </ul>
      </div>
    </div>
    <br>
    <table class="bordered-table zebra-striped">
      <thead>
        <th> # </th>
        <th>Report type</th>
        <th>Name</th>
        <th>Designation</th>
        <th>Status</th>
        <th>Created at</th>
        <th>Has Map</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report.id %> </td>
            <td><%= report.report_type.name %></td>
            <td><%= report.general_report.name %></td>
            <td><%= report.general_report.designation %></td>
            <td><%= report.status_report.status.name %></td>
            <td><%= report.created_at.strftime('%d %b %Y') %></td>
            <td><%= report.location_report.has_map? ? "Yes" : "No" %></td>
            <td>
              <%= link_to 'Show', report, :class => 'btn info' %>
              <%= link_to 'Edit', edit_report_path(report), :class => 'btn' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/reports/new.html.erb
<%= render 'form' %>

app/views/reports/show.html.erb
<div class="container-fluid">
  <div class="sidebar">
    <div class="header indent1">
      <h1> 
        Sidebar
      </h1>
    </div>
    <div class="clearfix">
      <div class="created">
        <strong>Created on </strong><%= @report.created_at.strftime('%d of %B, %Y') %> by 
        <em><%= @report.created_by.try(:username) || "No data" %></em>
      </div> 
      <div class="updated">
        <strong>Updated on</strong> <%= @report.updated_at.strftime('%d of %B, %Y') %> by 
        <em><%= @report.updated_by.try(:username) || "No data" %></em>
      </div>
      <div class="clearfix">
        <%= link_to 'Edit', edit_report_path(@report), :class => 'btn info' %>
        <%= link_to 'Delete', @report, :method => :delete, :confirm => "Are you sure?", :class => 'btn danger'  %> 
        <%= link_to 'Back', reports_path, :class => 'btn' %>
      </div>
    </div>
  </div>  
  <div class="content">
    <div class="header indent1">
      <h1> 
        Report : <%= @report.report_type.name %> 
      </h1>
    </div>
    <section id="user"></section>
    <section id="general">
      <%= render :partial => 'reports/information/general_report', :locals => { :general => @report.general_report } %>
    </section>
    <section id="owner">
      <%= render :partial => 'reports/information/owner_report', :locals => { :owner => @report.owner_report } %>
    </section>
    <section id="historical">
      <%= render :partial => 'reports/information/historical_report', :locals => { :historical => @report.historical_report } %>
    </section>
    <section id="location">
      <%= render :partial => 'reports/information/location_report', :locals => { :location => @report.location_report } %>
    </section>
    <section id="status">
      <%= render :partial => 'reports/information/status_report', :locals => { :status => @report.status_report } %>
    </section>
    <section id="supplementary_data">
      <%= render :partial => 'reports/information/supplementary_data_report', :locals => { :supplementary_data => @report.supplementary_data_report } %>
    </section>
    <section id="technical_card">
      <%= render :partial => 'reports/information/technical_card_report', :locals => { :technical_card => @report.technical_card_report } %>
    </section>
  </div>
</div>